app: multi-scf
stage: dev

component: multi-scf
name: demo

inputs:
  src:
    src: ./
    exclude:
      - .env
  region: ap-guangzhou
  runtime: Nodejs12.16
  memorySize: 128
  timeout: 3
  functions:
    - name: index
      handler: app.index
    - name: userList
      handler: app.userList
      memorySize: 256
      timeout: 10
  triggers:
    - type: timer
      function:
        name: index
      parameters:
        name: timer1
        cronExpression: '*/5 * * * * * *' # 每5秒触发一次
        enable: true
        argument: argument # 额外的参数
    - type: apigw
      parameters:
        name: serverless
        protocols:
          - https
          - http
        # id: service-xxx # 如果不配置，会自动创建
        apis:
          - path: /
            method: GET
            # api 的 function 配置优先级高于外层 function
            function:
              name: index
          - path: /
            method: POST
            function:
              name: userList
